function [ximg1,ximg2] = getVisionScanner(app)
    if app.sensor1Handle == 0 || app.sensor2Handle == 0
        [err,app.sensor1Handle] = app.sim.simxGetObjectHandle(0, 'SICK_S300_sensor1',...
        app.sim.simx_opmode_blocking);
        [err,app.sensor2Handle] = app.sim.simxGetObjectHandle(0, 'SICK_S300_sensor2',...
        app.sim.simx_opmode_blocking);
        app.sim.simxSynchronousTrigger(app.clientID);
        [err,res,img1] =...
        app.sim.simxGetVisionSensorImage2(0, app.sensor1Handle,...
            1, app.sim.simx_opmode_streaming);
        [err,res,img2] =...
        app.sim.simxGetVisionSensorImage2(0, app.sensor2Handle,...
            1, app.sim.simx_opmode_streaming);
        pause(0.1);
    end

    [err,res,img1] =...
        app.sim.simxGetVisionSensorImage2(0, app.sensor1Handle,...
            1, app.sim.simx_opmode_buffer);
    [err,res,img2] =...
        app.sim.simxGetVisionSensorImage2(0, app.sensor2Handle,...
            1, app.sim.simx_opmode_buffer);
    ximg1 = double(img1)/256;
    ximg2 = double(img2)/256;
end