function [ximg1,ximg2] = getVisionScanner(app)
    [err,sensor1] = app.sim.simxGetObjectHandle(0, 'SICK_S300_sensor1',...
        app.sim.simx_opmode_oneshot_wait);
    [err,sensor2] = app.sim.simxGetObjectHandle(0, 'SICK_S300_sensor2',...
        app.sim.simx_opmode_oneshot_wait);
    [err,res,img1] =...
        app.sim.simxGetVisionSensorImage2(0, sensor1,...
            1, app.sim.simx_opmode_oneshot_wait);
    [err,res,img2] =...
        app.sim.simxGetVisionSensorImage2(0, sensor2,...
            1, app.sim.simx_opmode_oneshot_wait);
    ximg1 = double(img1)/256;
    ximg2 = double(img2)/256;
end